name: fix-code-syntax

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  fix-code-syntax:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🧩 Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # ensures full git history for commits

      - name: 🧰 Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: 🧱 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: 📦 Install dependencies
        run: |
          composer install --optimize-autoloader --no-progress --no-interaction --prefer-dist
          npm ci

      - name: Lint Application
        run: composer lint

      - name: Run Prettier
        run: npm run prettier

      - name: ✅ Check for changes
        id: git_diff
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: 💾 Commit and push changes
        if: steps.git_diff.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: fix code style [skip ci]"
          file_pattern: >
            app/ config/ database/ public/ resources/ routes/ tests/
            *.php *.json *.js *.css
